### PR TITLE
fix: Correct unbounded ripple diameter

### LINKED ISSUE #1067: Correct unbounded ripple diameter
### What MDC-Web Version are you using?

> 0.16.0

### What browser(s) is this bug affecting?

> All browsers (Chrome newest)

### What OS are you using?

> All OS (Windows 7, Android 7)

### What are the steps to reproduce the bug?

> 1. Add a ripple to the toolbar icons
> 2. Observe the component's behavior
>
> https://codepen.io/anon/pen/YxGLQE

### What is the expected behavior?

> The ripple should be close to the size of the icon.

### What is the actual behavior?

> The ripple is a lot bigger than what it should be.

### PR DESCRIPTION
**Pull request by touficbatache**
Fixes and closes #1067

### CODE REVIEW

File: packages/mdc-ripple/foundation.js [hunk 1]
```diff
@@ -471,7 +471,7 @@ export default class MDCRippleFoundation extends MDCFoundation {
     this.frame_ = this.adapter_.computeBoundingRect();
 
     const maxDim = Math.max(this.frame_.height, this.frame_.width);
-    const surfaceDiameter = Math.sqrt(Math.pow(this.frame_.width, 2) + Math.pow(this.frame_.height, 2));
+    const surfaceDiameter = this.frame_.width;
```
Comment (yeelan0319) [inline packages/mdc-ripple/foundation.js]: I suggest we change this to `Math.min(this.frame_.width, this.frame_.height)` so when unbounded ripple is applied to non-square surface, it will always start within the container.

**Comment by touficbatache** [comment]
Yes sure, done!

File: packages/mdc-ripple/foundation.js (hunk 1 above)
Comment (touficbatache) [inline packages/mdc-ripple/foundation.js]: Yes sure, done!

**Comment by touficbatache** [comment]
@yeelan0319 No problem, happy to be a part of the community :smiley:
