### PR TITLE
fix(icon-button): update event handling to new standard

### LINKED ISSUE #3162: Update Icon Button toggle event to match new event handler pattern
Icon button component should not use the #adapter.registerEventHandler or #adapter.deregisterEventHandler methods. Instead convert the private `#foundation.toggleFromEvt_` to a public `#handleClick`.

### PR DESCRIPTION
**Pull request by moog16**
fixes #3162

### CODE REVIEW

File: packages/mdc-icon-button/foundation.js [hunk 1]
```diff
@@ -61,18 +61,10 @@ class MDCIconButtonToggleFoundation extends MDCFoundation {
```
Comment (bonniezhou) [inline packages/mdc-icon-button/foundation.js]: Remove `[de]registerInteractionHandler` from `get defaultAdapter()`, and from the adapter interface file

File: test/unit/mdc-icon-button/foundation.test.js [hunk 2]
```diff
@@ -56,6 +56,20 @@ test('#constructor sets on to true if the toggle is pressed', () => {
   assert.isTrue(foundation.isOn());
 });
 
+test('#handleClick calls #toggle', () => {
+  const {foundation, mockAdapter} = setupTest();
+  foundation.init();
+  foundation.handleClick();
+  td.verify(mockAdapter.setAttr('aria-pressed', 'true'), {times: 1});
```
Comment (bonniezhou) [inline test/unit/mdc-icon-button/foundation.test.js]: I think this should verify that `foundation.toggle()` was called. The aria-pressed is verified in another test.

File: test/unit/mdc-icon-button/mdc-icon-button-toggle.test.js [hunk 3]
```diff
@@ -189,3 +167,20 @@ test('assert keyup does not trigger ripple', () => {
...
+
+test('click handler is added to root element', () => {
+  const {root, component} = setupTest();
+  component.foundation_.handleClick = td.func();
+
+  domEvents.emit(root, 'click');
+  td.verify(component.foundation_.handleClick(), {times: 1});
+});
+
+test('keydown handler is removed from the root element on destroy', () => {
```
Comment (kfranqueiro) [inline test/unit/mdc-icon-button/mdc-icon-button-toggle.test.js]: keydown -> click
