### PR TITLE
Select option list follows page scroll

### LINKED ISSUE #879: When the user opens `select`, and scroll, the screen will move.
### What MDC-Web Version are you using?

v0.14.0

### What browser(s) is this bug affecting?

All browsers

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

https://material-components-web.appspot.com/select.html

### What is the expected behavior?

When the user opens `select`, the body's scroll bar should not be scrolled.

### What is the actual behavior?

When the user opens `select`, and scroll, the screen will move.

### Any other information you believe would be useful?

Ref: https://material.angular.io/components/select/overview

### PR DESCRIPTION
**Pull request by roncapat**
Fixes #879.

### CODE REVIEW

File: scripts/rewrite-decl-statements-for-closure-test.js [hunk 1]
```diff
@@ -22,7 +22,7 @@
  *  * Rewrite import Foo from './foo' to const Foo = goog.require('mdc.foo')
  *  * Rewrite import {foo, bar} from './util' to const {foo, bar} = goog.require('mdc.util')
  *
- *
```
Comment (roncapat) [inline scripts/rewrite-decl-statements-for-closure-test.js]: Running `npm run lint` resulted in an error pointing to this line. I noticed that on TravisCI, and so I made this fix to let the validation process continue.

File: packages/mdc-select/mdc-select.scss [hunk 2]
```diff
@@ -133,6 +133,9 @@
 // postcss-bem-linter: end
 
 .mdc-select__menu {
```
Comment (touficbatache) [inline packages/mdc-select/mdc-select.scss]: Could you please make those changes on line 82 instead?

File: packages/mdc-select/mdc-select.scss [hunk 3]
```diff
@@ -133,6 +133,9 @@
...
+  position: absolute;
+  z-index: 3;
```
Comment (touficbatache) [inline packages/mdc-select/mdc-select.scss]: The menu already has a `z-index` of 4

File: packages/mdc-select/mdc-select.scss [hunk 4]
```diff
@@ -133,6 +133,9 @@
 // postcss-bem-linter: end
 
 .mdc-select__menu {
+  position: absolute;
```
Comment (touficbatache) [inline packages/mdc-select/mdc-select.scss]: Don't add a new one, just edit the the `position: fixed` on line 83

File: packages/mdc-select/mdc-select.scss (hunk 3 above)
Comment (roncapat) [reply packages/mdc-select/mdc-select.scss]: So it's normal that it goes above the header?

Comment (touficbatache) [reply packages/mdc-select/mdc-select.scss]: Hmm, I'm not sure. Setting its `z-index` to 3 may make it go under some other components.

Comment (roncapat) [reply packages/mdc-select/mdc-select.scss]: So I'll leave value 4 in order to avoid some unnoticed changes of behaviour in other situations for now.

File: packages/mdc-select/mdc-select.scss (hunk 2 above)
Comment (roncapat) [reply packages/mdc-select/mdc-select.scss]: see d4af29d

**Comment by roncapat** [comment]
Changes implemented as for the drawer, it works!

A little problem while linting:
```
packages/mdc-select/mdc-select.scss
 262:1  ✖  Invalid component selector ".mdc-select-scroll-lock"   plugin/selector-bem-pattern
```

However I used the same convention of `mdc-drawer-scroll-lock` or am I missing something?

**Comment by roncapat** [comment]
Forgot to update tests! I'll try

File: packages/mdc-select/mdc-select.scss [hunk 5]
```diff
@@ -80,7 +80,7 @@
   }
 
   &__menu {
-    position: fixed;
+    position: absolute;
```
Comment (touficbatache) [inline packages/mdc-select/mdc-select.scss]: Why are you changing the position fixed to position absolute? It's not necessary as the body will not be scrollable :smiley:

Comment (roncapat) [reply packages/mdc-select/mdc-select.scss]: You're right :smile: I'm pushing the commit that reverts the position value

**Comment by touficbatache** [comment]
While we're at it, could you make the same for `mdc-menu`? Don't do it now though, wait for someone from the developers to agree with me first :smiley:

**Comment by roncapat** [comment]
Of course :) I'll wait. I'm happy to contribute as much as I can.

Il sab 28 ott 2017, 13:33 Toufic Batache <notifications@github.com> ha
scritto:

**Comment by roncapat** [comment]
> While we're at it, could you make the same for mdc-menu? Don't do it now though, wait for someone from the developers to agree with me first

@touficbatache what does prevent this PR from being merged?
I can do the work for `mdc-menu` in another PR if requested :+1:

**Comment by touficbatache** [comment]
Nothing, you just have to wait for someone to merge it :smiley:

File: package.json [hunk 6]
```diff
@@ -62,7 +62,7 @@
     "karma-coverage": "^1.1.0",
     "karma-firefox-launcher": "^1.0.0",
     "karma-mocha": "^1.3.0",
-    "karma-sauce-launcher": "^1.0.0",
+    "karma-sauce-launcher": "^1.2.0",
```
Comment (lynnjepsen) [inline package.json]: Take this out of this PR

File: packages/mdc-button/_mixins.scss [hunk 7]
```diff
@@ -102,6 +102,7 @@
   -webkit-appearance: none;
   overflow: hidden;
   vertical-align: middle;
+  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
```
Comment (lynnjepsen) [inline packages/mdc-button/_mixins.scss]: And remove this from this PR

File: packages/mdc-checkbox/_mixins.scss [hunk 8]
```diff
@@ -156,8 +156,8 @@
   &-checked-unchecked,
   &-indeterminate-unchecked {
     .mdc-checkbox__background {
-      animation-duration: $mdc-checkbox-transition-duration * 2;
       animation-timing-function: linear;
+      animation-duration: $mdc-checkbox-transition-duration * 2;
```
Comment (lynnjepsen) [inline packages/mdc-checkbox/_mixins.scss]: And remove this from this PR

File: packages/mdc-select/mdc-select.scss [hunk 9]
```diff
@@ -264,3 +264,8 @@
 // with CSS. Use the font-size rule instead.
 
 // postcss-bem-linter: end
+
+.mdc-select-scroll-lock {
+  height: 100vh;
```
Comment (lynnjepsen) [inline packages/mdc-select/mdc-select.scss]: why do you need to set the hight? Is `overflow: hidden` not enough to remove the scroll bar?

File: packages/mdc-theme/_color-palette.scss [hunk 10]
```diff
@@ -59,7 +59,7 @@ $material-color-purple-900: #4a148c;
 $material-color-purple-a100: #ea80fc;
 $material-color-purple-a200: #e040fb;
 $material-color-purple-a400: #d500f9;
-$material-color-purple-a700: #aa00ff;
+$material-color-purple-a700: #a0f;
```
Comment (lynnjepsen) [inline packages/mdc-theme/_color-palette.scss]: And remove this from this PR

File: packages/mdc-select/index.js [hunk 11]
```diff
@@ -112,6 +112,8 @@ export class MDCSelect extends MDCComponent {
       deregisterMenuInteractionHandler: (type, handler) => this.menu_.unlisten(type, handler),
       notifyChange: () => this.emit(MDCSelectFoundation.strings.CHANGE_EVENT, this),
       getWindowInnerHeight: () => window.innerHeight,
+      addBodyClass: (className) => document.body.classList.add(className),
```
Comment (lynnjepsen) [inline packages/mdc-select/index.js]: why do you add this class to the document body? Why can't this class be added directly to the this.root_ element?

Comment (touficbatache) [reply packages/mdc-select/index.js]: He is looking at the same implementation for the drawer and doing the same here :smiley:

File: packages/mdc-select/mdc-select.scss (hunk 9 above)
Comment (touficbatache) [reply packages/mdc-select/mdc-select.scss]: It's just like that in the drawer implementation

**Comment by roncapat** [comment]
@lynnjepsen @touficbatache what should I do for the discussed changes above? I saw your comments, and personally I've done the same of drawer implementation, so no design choices here but just a re-implementation. I've done the other fixes @lynnjepsen requested, of course, but leaved the two discussed changes untouched by now.

File: packages/mdc-select/index.js (hunk 11 above)
Comment (lynnjepsen) [reply packages/mdc-select/index.js]: thanks for the context @touficbatache

File: packages/mdc-select/mdc-select.scss (hunk 9 above)
Comment (lynnjepsen) [reply packages/mdc-select/mdc-select.scss]: I did some digging into the drawer (and dialog for that matter) and we're 99% sure that `height: 100vh` is unnecessary. 

So, @roncapat, go ahead and remove it here too. (#1610 and #1612 for the changes we're making to drawer and dialog)

File: packages/mdc-checkbox/_mixins.scss [hunk 12]
```diff
@@ -156,7 +156,6 @@
   &-checked-unchecked,
   &-indeterminate-unchecked {
     .mdc-checkbox__background {
-      animation-duration: $mdc-checkbox-transition-duration * 2;
```
Comment (lynnjepsen) [inline packages/mdc-checkbox/_mixins.scss]: this changes seems to have sneaked into this PR...can you make sure packages/mdc-checkbox/_mixins.scss is the exact same as our master branch?

File: packages/mdc-theme/_color-palette.scss [hunk 13]
```diff
@@ -207,7 +207,7 @@ $material-color-yellow-700: #fbc02d;
 $material-color-yellow-800: #f9a825;
 $material-color-yellow-900: #f57f17;
 $material-color-yellow-a100: #ffff8d;
-$material-color-yellow-a200: #ffff00;
+$material-color-yellow-a200: #ff0;
```
Comment (lynnjepsen) [inline packages/mdc-theme/_color-palette.scss]: this changes seems to have sneaked into this PR...can you make sure packages/mdc-theme/_color-palette.scss is the exact same as our master branch?

File: packages/mdc-select/mdc-select.scss (hunk 9 above)
Comment (roncapat) [reply packages/mdc-select/mdc-select.scss]: IMHO, if we remove `height: 100vh`, scroll will be permitted and so select menu overlay won't follow the base selector on page. (I've done the changes you requested, but I have to test the behaviour).

**Comment by roncapat** [comment]
@lynnjepsen I've done chances and tested. It works.
