### PR TITLE
fix(top-app-bar): "always collapsed" variant semantics in Short TopAppBar Foundation

### LINKED ISSUE #4928: TopAppBar short never reopens after initial scroll
### Steps to reproduce
1. Go to https://material.io/develop/web/components/top-app-bar/
2. Scroll down to the "short" variant of the top-app-bar
3. Scroll down, notice it shrinks
4. Scroll back to top, notice it does not restore to its original full size

### Expected behavior
The top-app-bar should restore to its original size for the short variant whenever the page is scrolled back to the top

Noticed this while upgrading RMWC to 3.0.0. I don't believe this was an issue with 2.0.0

### PR DESCRIPTION
**Pull request by azakus**
- Add `setAlwaysCollapsed(value: boolean)` and `getAlwaysCollapsed()`
  methods
- Keep behavior of initializing with `SHORT_COLLAPSED_CLASS` to mean
  that the component should always be collapsed.

Fixes #4928

### CODE REVIEW

File: packages/mdc-top-app-bar/short/foundation.ts [hunk 1]
```diff
@@ -45,33 +47,61 @@ export class MDCShortTopAppBarFoundation extends MDCTopAppBarBaseFoundation {
...
+   * When set to `true`, the bar collapses.
+   * When set to `false`, the bar will determine if it should collapse based on scroll position.
+   */
+  setAlwaysCollapsed(value: boolean) {
+    this.isAlwaysCollapsed_ = !!value;
+    if (this.isAlwaysCollapsed_) {
+      this.collapse_();
+    } else {
+      // let handleTargetScroll determine if the bar should be collapsed
+      this.handleTargetScroll();
```
Comment (abhiomkar) [inline packages/mdc-top-app-bar/short/foundation.ts]: Ideally handle* methods should be called by component. This might short circuit in future if we introduce any additional logic to handleTargetScroll.

Can we abstract out the required logic from `handleTargetScroll` which can be called here?

File: packages/mdc-top-app-bar/short/foundation.ts [hunk 2]
```diff
@@ -45,33 +47,61 @@ export class MDCShortTopAppBarFoundation extends MDCTopAppBarBaseFoundation {
...
+      this.adapter_.hasClass(cssClasses.SHORT_COLLAPSED_CLASS));
+  }
+
+  /**
+   * Set if the short top app bar should always be collapsed.
+   *
+   * When set to `true`, the bar collapses.
+   * When set to `false`, the bar will determine if it should collapse based on scroll position.
+   */
+  setAlwaysCollapsed(value: boolean) {
```
Comment (abhiomkar) [inline packages/mdc-top-app-bar/short/foundation.ts]: Please add unit tests.

File: packages/mdc-top-app-bar/short/foundation.ts [hunk 3]
```diff
@@ -45,33 +47,61 @@ export class MDCShortTopAppBarFoundation extends MDCTopAppBarBaseFoundation {
...
     } else {
       if (!this.isCollapsed_) {
-        this.adapter_.addClass(cssClasses.SHORT_COLLAPSED_CLASS);
-        this.isCollapsed_ = true;
+        this.collapse_();
       }
     }
   }
+
+  private uncollapse_() {
```
Comment (abhiomkar) [inline packages/mdc-top-app-bar/short/foundation.ts]: Did you test this in screenshot demo: test/screenshot/spec/mdc-top-app-bar/classes/baseline-short.html ?

Comment (azakus) [reply packages/mdc-top-app-bar/short/foundation.ts]: Yep: https://storage.googleapis.com/mdc-web-screenshot-tests/dfreedm/2019/08/19/23_45_33_613/report/report.html?utm_source=cli&utm_medium=test_results

File: packages/mdc-top-app-bar/short/foundation.ts (hunk 1 above)
Comment (azakus) [reply packages/mdc-top-app-bar/short/foundation.ts]: Done. Moved internals of `handleTargetScroll` into a private function `maybeCollapseBar_`

File: packages/mdc-top-app-bar/short/foundation.ts (hunk 2 above)
Comment (azakus) [reply packages/mdc-top-app-bar/short/foundation.ts]: Done.

File: packages/mdc-top-app-bar/short/foundation.ts [hunk 4]
```diff
@@ -45,33 +47,65 @@ export class MDCShortTopAppBarFoundation extends MDCTopAppBarBaseFoundation {
...
-    this.handleTargetScroll();
+    // If initialized with SHORT_COLLAPSED_CLASS, the bar should always be collapsed
+    this.setAlwaysCollapsed(
+      this.adapter_.hasClass(cssClasses.SHORT_COLLAPSED_CLASS));
+  }
+
+  /**
+   * Set if the short top app bar should always be collapsed.
+   *
+   * When set to `true`, the bar collapses.
```
Comment (abhiomkar) [inline packages/mdc-top-app-bar/short/foundation.ts]: Add TSDoc for `@param`

File: packages/mdc-top-app-bar/short/foundation.ts [hunk 5]
```diff
@@ -45,33 +47,65 @@ export class MDCShortTopAppBarFoundation extends MDCTopAppBarBaseFoundation {
...
    * Scroll handler for applying/removing the collapsed modifier class on the short top app bar.
    * @override
    */
   handleTargetScroll() {
-    if (this.adapter_.hasClass(cssClasses.SHORT_COLLAPSED_CLASS)) {
+    this.maybeCollapseBar_();
+  }
+
+  private maybeCollapseBar_() {
+    if (this.isAlwaysCollapsed_) {
```
Comment (abhiomkar) [inline packages/mdc-top-app-bar/short/foundation.ts]: This condition is already covered in `setAlwaysCollapsed`? is this specific to `handleTargetScroll`?

**Comment by azakus** [comment]
> Since this is a breaking change it should be merged to `develop` branch.

Can you say why you consider this a breaking change? I've been trying to keep behavior the same.

**Comment by azakus** [comment]
> Also scope the PR title and commit message title (when you squash-and-merge) to `fix(top-app-bar): ...` for purpose of changelog.

Done

**Comment by abhiomkar** [comment]
> Can you say why you consider this a breaking change? I've been trying to keep behavior the same.

My bad, we added new foundation method which are totally optional. Yes, this is not a breaking change.

File: packages/mdc-top-app-bar/short/foundation.ts (hunk 5 above)
Comment (azakus) [reply packages/mdc-top-app-bar/short/foundation.ts]: Yes. This will short circuit the scroll handler, and keep the bar collapsed.

File: packages/mdc-top-app-bar/short/foundation.ts (hunk 4 above)
Comment (azakus) [reply packages/mdc-top-app-bar/short/foundation.ts]: Done.
