### PR TITLE
fix(menu): Close menu even when a list-item was clicked.

### LINKED ISSUE #1747: Select menu does not close when clicking
### What MDC-Web Version are you using?

0.27.0

### What browser(s) is this bug affecting?

Crome 62.0.3202.94 and any browser

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1. Go to https://codepen.io/YuoMamoru/full/rpNxMB
2. Click a "mdc-select" in the page
3. Click the list under "Steps to Reproduce the Bug"

### What is the expected behavior?

If you click the point on "li" tag with class="mdc-list-item", the menu should close.

### What is the actual behavior?

If you click the point on "li" tag with class="mdc-list-item", the menu does not close.

### Any other information you believe would be useful?

I think that it is an issue not to check whether the element clicked is part of its own menu in handleDocumentClick_(evt) on mdc-menu/simple/foundation.js.

### PR DESCRIPTION
**Pull request by simono**
Previously clicks on a list-item in the page would leave the menu open. Now we check if a item in this menu was clicked and leave the menu open.

Fixes #1747 

@amsheehan You introduced this behavior in 02fe795139. Is my fix correct?

### CODE REVIEW

File: packages/mdc-menu/simple/foundation.js [hunk 1]
```diff
@@ -282,7 +281,7 @@ class MDCSimpleMenuFoundation extends MDCFoundation {
     let el = evt.target;
 
     while (el && el !== document.documentElement) {
-      if (this.adapter_.eventTargetHasClass(el, cssClasses.LIST_ITEM)) {
+      if (this.adapter_.getIndexForEventTarget(el) >= 0) {
```
Comment (patrickrodee) [inline packages/mdc-menu/simple/foundation.js]: Small nitpick: I'd suggest updating the JSDoc description to explain that it cancels if it's not a child item instead of just a list item.

Comment (patrickrodee) [reply packages/mdc-menu/simple/foundation.js]: Also, perhaps just personal preference, but I prefer checks to be as explicit as possible so it might be a good idea to change the comparator from `>= 0` to `!== -1`

**Comment by simono** [comment]
@patrickrodee Thanks for the Review. I updated the PR.

**Comment by simono** [comment]
@patrickrodee I rebase my branch on master. Anything else I can do to get this merged? Thanks!

**Comment by simono** [comment]
@williamernest I rebased my branch once again and it should apply cleanly now. Let me know if there's anything I can help out with. Thanks!
