### PR TITLE
fix(select): Fix enhanced select issue where it does not stay open on long press #4173

### LINKED ISSUE #4173: Enhanced select menu doesn't stay open
When using the the enhanced version of the mdc-select menu (v. 0.42.0), the menu-list immediately disappears. One would expect the menu to stay open until it loses focus.

This behavior can also be seen @ https://material-components.github.io/material-components-web-catalog/#/component/select , at least on my computer (mac os mojave, chrome v 71).

### PR DESCRIPTION
**Pull request by moog16**
continuation of https://github.com/material-components/material-components-web/pull/4413
fixes #4173

### CODE REVIEW

File: packages/mdc-select/component.ts [hunk 1]
```diff
@@ -37,9 +37,9 @@ import {MDCSelectHelperText, MDCSelectHelperTextFactory} from './helper-text/ind
 import {MDCSelectIcon, MDCSelectIconFactory} from './icon/index';
 import {MDCSelectEventDetail, MDCSelectFoundationMap} from './types';
 
-type PointerEventType = 'mousedown' | 'touchstart';
+type PointerEventType = 'click';
```
Comment (abhiomkar) [inline packages/mdc-select/component.ts]: We not longer need `POINTER_EVENTS` & `PointerEventType` since this is only single event, we can directly add register it to handleClick foundation method without looping through `POINTER_EVENTS`.

**Comment by moog16** [comment]
@shelart could you comment here and say "I signed it" please

**Comment by shelart** [comment]
I signed it
