### PR TITLE
fix(checkbox): remove register/deregisterEventlisteners from foundation

### LINKED ISSUE #2813: Remove [de]registerEventHandler methods from adapters
Our adapters often have `registerEventHandler`/`deregisterEventHandler` methods that are used to add and remove event listeners from DOM nodes. Many frameworks (React, Angular, Vue, etc) prefer events to be bound directly on the DOM elements. This has the benefit of not requiring references to the DOM in the component lifecycle and ensuring that the event handlers are appropriately cleaned up on component destruction.

For many of those frameworks, the `registerEventHandler`/`deregisterEventHandler` adapter methods become no-ops.

We should remove the `registerEventHandler`/`deregisterEventHandler` methods from our adapters and instead expose information about which handlers should be bound to which events. Registering the event handlers will then become the responsibility of those who wrap our components.

Packages that may require updates, as of 5/29/18:

* [x] checkbox
* [x] chips
* [x] dialog
* [x] drawer
* [ ] floating-label
* [ ] form-field
* [ ] grid-list
* [x] icon-button (which replaces icon-toggle)
* [ ] line-ripple
* [x] menu
* [ ] radio
* [ ] ripple
* [x] select
* [ ] slider
* [x] snackbar
* [ ] top-app-bar (which replaces toolbar)
* [x] tab
* [x] tab-indicator
* [ ] text-field and text-field icon

### PR DESCRIPTION
**Pull request by moog16**
refs #2813

### CODE REVIEW

File: packages/mdc-checkbox/index.js [hunk 1]
```diff
@@ -56,6 +56,17 @@ class MDCCheckbox extends MDCComponent {
...
+    this.handleChange_;
+    /** @private {!Function} */
+    this.handleAnimationEnd_;
+  }
+
+  initialSyncWithDOM() {
+    this.handleChange_ = () => this.foundation_.handleChange();
+    this.handleAnimationEnd_= () => this.foundation_.handleAnimationEnd();
+    this.nativeCb_.addEventListener('change', this.handleChange_);
+    this.root_.addEventListener(getCorrectEventName(window, 'animationend'), this.handleAnimationEnd_);
```
Comment (kfranqueiro) [inline packages/mdc-checkbox/index.js]: Change this to `this.listen` (since you're using `unlisten` in destroy anyway)

File: packages/mdc-checkbox/foundation.js [hunk 2]
```diff
@@ -297,6 +291,8 @@ class MDCCheckboxFoundation extends MDCFoundation {
       this.adapter_.setNativeControlAttr(
         strings.ARIA_CHECKED_ATTR, strings.ARIA_CHECKED_INDETERMINATE_VALUE);
     } else {
+      // the on/off state does not need to keep track of aria-checked, since
```
Comment (kfranqueiro) [inline packages/mdc-checkbox/foundation.js]: Nit: Capitalize `The`

File: test/unit/mdc-checkbox/mdc-checkbox.test.js [hunk 3]
```diff
@@ -139,6 +138,36 @@ test('get ripple returns a MDCRipple instance', () => {
...
+});
+
+test('root animationend event calls #foundation.handleAnimationEnd', () => {
+  const {root, component} = setupTest();
+  component.foundation_.handleAnimationEnd = td.func();
+  domEvents.emit(root, 'animationend');
+  td.verify(component.foundation_.handleAnimationEnd(), {times: 1});
+});
+
+test('checkbox change event is destroyed on #destroy', () => {
```
Comment (kfranqueiro) [inline test/unit/mdc-checkbox/mdc-checkbox.test.js]: event _handler_ is destroyed

File: test/unit/mdc-checkbox/mdc-checkbox.test.js [hunk 4]
```diff
@@ -139,6 +138,36 @@ test('get ripple returns a MDCRipple instance', () => {
...
+  const {cb, component} = setupTest();
+  component.foundation_.handleChange = td.func();
+  component.destroy();
+  domEvents.emit(cb, 'change');
+  td.verify(component.foundation_.handleChange(), {times: 0});
+});
+
+test('root animationend event is destroyed on #destroy', () => {
```
Comment (kfranqueiro) [inline test/unit/mdc-checkbox/mdc-checkbox.test.js]: event _handler_ is destroyed

File: packages/mdc-checkbox/index.js [hunk 5]
```diff
@@ -81,11 +92,6 @@ class MDCCheckbox extends MDCComponent {
       removeClass: (className) => this.root_.classList.remove(className),
       setNativeControlAttr: (attr, value) => this.nativeCb_.setAttribute(attr, value),
       removeNativeControlAttr: (attr) => this.nativeCb_.removeAttribute(attr),
-      registerAnimationEndHandler:
-        (handler) => this.root_.addEventListener(getCorrectEventName(window, 'animationend'), handler),
-      deregisterAnimationEndHandler:
-        (handler) => this.root_.removeEventListener(getCorrectEventName(window, 'animationend'), handler),
-      registerChangeHandler: (handler) => this.nativeCb_.addEventListener('change', handler),
```
Comment (kfranqueiro) [inline packages/mdc-checkbox/index.js]: You forgot to remove `deregisterChangeHandler` (I noticed because coverage found it uncovered, but it shouldn't be here anymore)
