### PR TITLE
fix(textfield): Labels on single-line text fields support native browser autocomplete

### LINKED ISSUE #137: Single-line text fields do not work with auto-filled form fields
screen shot 2016-10-06 at 11 43 39 am

I tried detecting this via change events which didn't work. I also tried checking for `value` on init but that only worked for non-password inputs and was non-deterministic in terms of its timing.

Possible workarounds:
##### Style for `:autofill`

This is clearly the most elegant solution, but looks like it's [Chrome only](https://developer.mozilla.org/en-US/docs/Web/CSS/:-webkit-autofill)
##### Have elements poll to check if they're auto-filled

This will lead to the highest design fidelity, but is extremely inefficient and will incur a significant performance impact, especially on mobile browsers.
##### Tell users to set `autocomplete="off"`

This would in theory solve the problem. However, it is not only an inconvenience to the user, but it's [not guaranteed to work correctly](http://caniuse.com/#search=auto) for all types of input.
##### Tell users to only use JS-enhanced single-line inputs with form fields that won't be auto-completed

😢 

> Copied from https://github.com/google/material-design-lite/issues/4827

----

- [x] Summarize research on how most browsers handle auto-filling and present best solution
- [ ] Implement solution

### PR DESCRIPTION
**Pull request by amsheehan**
resolves #137

### CODE REVIEW

File: packages/mdc-textfield/foundation.js [hunk 1]
```diff
@@ -150,4 +156,20 @@ export default class MDCTextfieldFoundation extends MDCFoundation {
       disabled: false,
     };
   }
+
+  registerAutoCompleteHandler_(input) {
+    return new Promise((resolve, reject) => {
```
Comment (traviskaufman) [inline packages/mdc-textfield/foundation.js]: Did you happen to test this in IE11? Unfortunately, I don't think Promises are supported - http://caniuse.com/#feat=promises :( 

If that is the case, you could use a callback-based approach, e.g. `registerAutoCompleteHandler(onRegistered)` where `onRegistered` is your callback function.

File: packages/mdc-textfield/foundation.js [hunk 2]
```diff
@@ -65,9 +65,15 @@ export default class MDCTextfieldFoundation extends MDCFoundation {
   }
 
   init() {
+    const input = this.getNativeInput_();
+
     this.adapter_.addClass(MDCTextfieldFoundation.cssClasses.UPGRADED);
     this.adapter_.registerInputFocusHandler(this.inputFocusHandler_);
     this.adapter_.registerInputBlurHandler(this.inputBlurHandler_);
+    this.registerAutoCompleteHandler_(input)
+      .then((element) => {
```
Comment (traviskaufman) [inline packages/mdc-textfield/foundation.js]: do you need to have `(element)` as an arg here? Or can you just do `(() => this.activateFocus_())` ?

File: packages/mdc-textfield/mdc-textfield.scss [hunk 3]
```diff
@@ -116,6 +116,16 @@ $mdc-textfield-disabled-border-on-dark: rgba(white, .3);
   }
 }
 
+// Move label when textfield gets autofilled in Chrome
+.mdc-textfield__input {
+  // stylelint-disable plugin/selector-bem-pattern
+  &:-webkit-autofill + .mdc-textfield__label {
```
Comment (traviskaufman) [inline packages/mdc-textfield/mdc-textfield.scss]: If you use `&:autofill` here, does autoprefixer output the correct CSS?

File: packages/mdc-textfield/foundation.js [hunk 4]
```diff
@@ -150,4 +156,20 @@ export default class MDCTextfieldFoundation extends MDCFoundation {
       disabled: false,
     };
   }
+
+  registerAutoCompleteHandler_(input) {
+    return new Promise((resolve, reject) => {
+      let hasKeyInteraction = false;
+
+      input.addEventListener('input', (e) => {
```
Comment (traviskaufman) [inline packages/mdc-textfield/foundation.js]: Two things here:

1. We shouldn't be using `addEventListener` here directly on the input, since foundations should try to avoid using DOM API methods directly whenever possible. Instead, let's create a `registerInputKeyboardEventHandler(type, handler)` method similar to `registerInput{Focus,Blur}Handler` above that can accommodate for this, and then include it within the vanilla component. 

2. We need to clean up these handlers after they're used. I see this being done in two places: when the promise is resolved ( / callback is called, since we should change the method to be IE11-friendly), as well as in the foundation's `destroy()` method, in case the foundation is destroyed before the textfield is interacted with. In order to facilitate this let's make a complementary `deregisterInputKeyboardEventHandler(type, handler)` method, and then refactor the event handlers in this method as well as the `hasKeyInteraction` variable into instance properties. 

Since these are adapter changes, we also need to update the component to implement them, as well as the README to document them. Finally, since every adapter change is considered breaking, we have to remember to add a `BREAKING CHANGE:` footer to the final squash and merge commit.

File: packages/mdc-textfield/foundation.js [hunk 5]
```diff
@@ -150,4 +156,20 @@ export default class MDCTextfieldFoundation extends MDCFoundation {
...
+        if (!hasKeyInteraction) {
+          resolve(e);
```
Comment (traviskaufman) [inline packages/mdc-textfield/foundation.js]: do we need to call resolve with the event object? It doesn't look like we use it.

File: packages/mdc-textfield/foundation.js [hunk 6]
```diff
@@ -150,4 +156,20 @@ export default class MDCTextfieldFoundation extends MDCFoundation {
...
+        }
+      });
+
+      input.addEventListener('keydown', function(e) {
```
Comment (traviskaufman) [inline packages/mdc-textfield/foundation.js]: Do we need to have the event object passed into this function? It doesn't look like we use it.

Also, this should be a fat-arrow function.

```js
('keydown', () => {
  hasKeyInteraction = true;
});
```

File: packages/mdc-textfield/mdc-textfield.scss (hunk 3 above)
Comment (Garbee) [inline packages/mdc-textfield/mdc-textfield.scss]: Nope, it doesn't prefix autofill pseudos. You can test in [an online playground](https://autoprefixer.github.io/).

File: packages/mdc-textfield/foundation.js [hunk 7]
```diff
@@ -83,6 +100,16 @@ export default class MDCTextfieldFoundation extends MDCFoundation {
     this.showHelptext_();
   }
 
+  autoCompleteFocus_(keyInteraction) {
```
Comment (traviskaufman) [inline packages/mdc-textfield/foundation.js]: I feel like we don't need to pass in a `keyInteraction` argument here, since we already have `keyInteractionOccurred` as an instance property. So it can just be

```js
if (!this.keyInteractionOccurred) {
  this.activateFocus_();
}

File: packages/mdc-textfield/foundation.js [hunk 8]
```diff
@@ -83,6 +100,16 @@ export default class MDCTextfieldFoundation extends MDCFoundation {
...
+    if (!keyInteraction) {
+      this.activateFocus_();
+    }
+  }
+
+  setKeyInteraction_() {
+    this.keyInteractionOccurred = true;
```
Comment (traviskaufman) [inline packages/mdc-textfield/foundation.js]: What happens in the following scenario:

Say there are two text fields, and the following events happen:

1. User begins typing into first textfield
1. Browser auto-completes for both the first and second textfield
1. User clears second textfield
1. User goes back to first textfield and begins typing
1. Browser auto-completes both first and second textfield _again_

In this case, since `keyInteractionOccured` is already set to `true` from the first go-around, would the autocomplete functionality work as expected?

I think we might have to use some more detailed heuristics in order to get this to work correctly. For example, is the element currently focused might be a better indication of whether or not the input event was triggered by an auto-complete rather than a user interaction (since un-focused elements can only be `input` by means of an auto-complete, I would imagine).

File: packages/mdc-textfield/foundation.js [hunk 9]
```diff
@@ -60,20 +64,33 @@ export default class MDCTextfieldFoundation extends MDCFoundation {
 
   constructor(adapter = {}) {
     super(Object.assign(MDCTextfieldFoundation.defaultAdapter, adapter));
+
+    this.keyInteractionOccurred = false;
```
Comment (traviskaufman) [inline packages/mdc-textfield/foundation.js]: This should probably be a private property

File: test/unit/mdc-textfield/foundation.test.js [hunk 10]
```diff
@@ -105,6 +107,19 @@ test('#init adds mdc-textfield--upgraded class', (t) => {
   t.end();
 });
 
+test('#setKeyInteraction sets keyInteractionOccurred to true', (t) => {
```
Comment (traviskaufman) [inline test/unit/mdc-textfield/foundation.test.js]: We try not to test private methods, besides simply referencing `adapter_` in component tests. The reason is bc private methods are considered implementation details; a means to an end if you will. And what we really want is to be testing the ends. Specifically:

- Focused styles are applied when an `input` event is triggered on an element and no keydown was triggered beforehand (or, per the comment above,  some other means, such as if the element is not focused).

So it looks like that's just one single event test that should be implemented.

File: test/unit/mdc-textfield/foundation.test.js [hunk 11]
```diff
@@ -126,6 +141,34 @@ test('#destroy deregisters blur handler', (t) => {
...
+});
+
+test('#destroy deregisters keydown handler', (t) => {
+  const {foundation, mockAdapter} = setupTest();
+  foundation.destroy();
+  t.doesNotThrow(() => td.verify(mockAdapter.deregisterInputKeydownHandler(td.matchers.isA(Function))));
+  t.end();
+});
+
+test('#destroyAutoCompleteHandlers deregisters input handler', (t) => {
```
Comment (traviskaufman) [inline test/unit/mdc-textfield/foundation.test.js]: nit: The description here and below should be `#destroy deregisters ...`. We don't care about `#destroyAutoCompleteHandlers` since that's a private method and thus an implementation detail.

File: packages/mdc-textfield/foundation.js (hunk 8 above)
Comment (amsheehan) [inline packages/mdc-textfield/foundation.js]: I think you're right. What if we make `deactivateFocus()_` reset `keyInteractionOccurred` if the input value is an empty string. We already check for it in the method and I think it makes sense to add that to the list of concerns for `deactivateFocus()_`, and it solves for the above scenario.

File: test/unit/mdc-textfield/foundation.test.js (hunk 10 above)
Comment (amsheehan) [inline test/unit/mdc-textfield/foundation.test.js]: 👍

File: test/unit/mdc-textfield/foundation.test.js [hunk 12]
```diff
@@ -105,6 +107,37 @@ test('#init adds mdc-textfield--upgraded class', (t) => {
   t.end();
 });
 
+test('#on input focuses if input event occurs without any other events', (t) => {
```
Comment (traviskaufman) [inline test/unit/mdc-textfield/foundation.test.js]: micronit: `'on'` instead of `'#on`, usually we reserve `#` for testing public methods

Comment (amsheehan) [inline test/unit/mdc-textfield/foundation.test.js]: ahaaaa Thank you sir

**Comment by ranjeet-choudhary** [comment]
@amsheehan is this pull not available in master i'm facing issue with auto complete
