### PR TITLE
fix(text-field): Fix asterisk color of text field when input is invalid and disabled 

### LINKED ISSUE #4805: [TextField] The color of asterisk stays red when input is invalid and disabled.
### Steps to reproduce

1. Go to [text field demo on Glitch](https://glitch.com/edit/#!/mercury-tuesday?path=index.html:1:0).
2. Notice that textfields that are not initialized and disabled has red asterisk.

### Actual behavior

Asterisk is in red color even though input is disabled

### Expected behavior

Asterisk needs to be in grey color similar to floating label color when input is disabled.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | `v2.3.0`
| Browser          | All
| Operating System | All

### Possible solution

Set asterisk color on invalid excluding `--disabled` text fields.

### PR DESCRIPTION
**Pull request by abhiomkar**
Fixes #4805

### CODE REVIEW

File: test/screenshot/spec/mdc-textfield/fixture.js [hunk 1]
```diff
@@ -22,7 +22,7 @@
  */
 
 window.mdc.testFixture.fontsLoaded.then(() => {
-  [].forEach.call(document.querySelectorAll('.mdc-text-field'), (el) => {
+  [].forEach.call(document.querySelectorAll('.mdc-text-field:not([data-no-init="true"])'), (el) => {
```
Comment (moog16) [inline test/screenshot/spec/mdc-textfield/fixture.js]: Do we have anywhere in our docs that you shouldn't initialize a disabled text field?

Comment (abhiomkar) [reply test/screenshot/spec/mdc-textfield/fixture.js]: Internal implementation does not initialize the component until interacted. In that case asterisk would still be in red color.

Comment (moog16) [reply test/screenshot/spec/mdc-textfield/fixture.js]: I'm suggesting that we need to add some text to the Readme so that developers know not to initialize the text field until disabled is removed.

Comment (abhiomkar) [reply test/screenshot/spec/mdc-textfield/fixture.js]: Clients can definitely initialize text field even if it is disabled, why do you think they don't need to initialize when it is disabled?

Comment (moog16) [reply test/screenshot/spec/mdc-textfield/fixture.js]: I'm just wondering why you aren't initializing the text field.

Comment (moog16) [reply test/screenshot/spec/mdc-textfield/fixture.js]: I thought you said this morning that initializing it will remove `--invalid` class.

Comment (abhiomkar) [reply test/screenshot/spec/mdc-textfield/fixture.js]: Two reasons for this screenshot without initializing text field:

- Validates the styles (Only style without JS) for disabled & invalid state. Our screenshots are captured after JS execution that removes `--invalid` modifier from root. There might be some uses cases where clients do not need to initialize text field for some reason.
- Our internal implementation, we do not instantiate the foundation until the text field is interacted hence the asterisk stays red on page load which is unexpected. This test case should cover this case.
